A, B, C = input().split()
triangle = (1 / 2) * (float(A) * float(C))
print("TRIANGULO: %0.3f" % triangle)
circle = 3.14159 * (float(C) * float(C))
print("CIRCULO: %0.3f" % circle)
trapezium = ((float(A) + float(B)) / 2) * float(C)
print("TRAPEZIO: %0.3f" % trapezium)
square = float(B) * float(B)
print("QUADRADO: %0.3f" % square)
rectangle = float(A) * float(B)
print("RETANGULO: %0.3f" % rectangle)
